### ISSUE TITLE
Broken Links From CiviCRM Extension Page

### ISSUE THREAD

**Issue by mickadoo** [konadave/com.klangsoft.overrides#2]
When I click on any of the links to the ZIP files from https://civicrm.org/extensions/extension-file-overrides I get a 404 error.

I don't see any tags in this repo either, if there were tags to match the versions on that page I think Github will generate the tarballs for the tags anyway.

**Comment by konadave** [comment]
Don't know what happened to the old tags. Doesn't matter now, just released a new version.
