### ISSUE TITLE
Deprecation warning in PHP 7.4

### ISSUE THREAD

**Issue by wmortada** [konadave/com.klangsoft.overrides#4]
I'm getting the following error:

```
PHP Deprecated: Array and string offset access syntax with curly braces is deprecated in com.klangsoft.overrides/overrides.civix.php on line 246
```

Regenerating the civix file should fix this.

**Comment by magnolia61** [comment]
Error: Array and string offset access syntax with curly
braces is no longer supported in com.klangsoft.overrides/overrides.civix.php

Same here, any chance this extension can be updated?

**Comment by konadave** [comment]
New version doesn't have this problem.
